# Generated by Django 5.2 on 2025-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('result', models.TextField(verbose_name='Test Result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FecalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('result', models.TextField(verbose_name='Test Result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urinalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('result', models.TextField(verbose_name='Test Result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of vaccine')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Batch number')),
            ],
        ),
    ]
