# Generated by Django 5.2 on 2025-04-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        ('pets', '0002_alter_pet_passport_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, help_text='Time', null=True)),
                ('dosage', models.CharField(help_text='Specify dosage, e.g. "5mg twice a day"', max_length=50, verbose_name='Dosage')),
                ('duration', models.CharField(help_text='Specify duration, e.g. "7 days"', max_length=50, verbose_name='Duration')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.drug')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50, verbose_name='Batch number')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('manufacture_date', models.DateField(verbose_name='Manufacture date')),
                ('date_of_vaccination', models.DateField(verbose_name='Date of vaccination')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='pets.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.vaccine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_entry', models.DateField(verbose_name='Date of the entry')),
                ('doctor', models.CharField(max_length=100)),
                ('reason_for_visit', models.TextField(help_text='Description of the problem or reason for the visit', verbose_name='Reason for visit')),
                ('general_health', models.TextField(blank=True, null=True, verbose_name='General health')),
                ('body_condition_score', models.IntegerField(blank=True, help_text='Assessment of body condition (1 = underweight, 9 = obese)', null=True, verbose_name='Body Condition Score (1-9)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature of the animal', max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, verbose_name='Heart rate (bpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True, verbose_name='Respiratory rate')),
                ('mucous_membrane_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mucous Membrane Color')),
                ('hydration_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hydration Status')),
                ('skin_and_coat_condition', models.TextField(blank=True, null=True, verbose_name='Skin and Coat Condition')),
                ('teeth_and_gums', models.TextField(blank=True, null=True, verbose_name='Teeth and Gums')),
                ('eyes_ears_nose', models.TextField(blank=True, null=True, verbose_name='Eyes, Ears, and Nose')),
                ('treatment_performed', models.TextField(help_text='Description of the Treatment', verbose_name='Treatment Carried Out')),
                ('diagnosis', models.TextField(blank=True, help_text='Description of the final diagnosis', null=True, verbose_name='Diagnosis')),
                ('follow_up', models.BooleanField(default=False, verbose_name='Follow-up Required?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Examination Notes')),
                ('blood_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.bloodtest', verbose_name='Blood Test')),
                ('fecal_exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.fecalexam', verbose_name='Fecal Analysis')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_records', to='pets.pet')),
                ('urine_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.urinalysis', verbose_name='Urine Analysis')),
                ('medication', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='records.medicationrecord', verbose_name='Medications Prescribed')),
                ('vaccination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='records.vaccinationrecord', verbose_name='Vaccination Applied')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
