# Generated by Django 5.2 on 2025-04-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('pets', '0002_alter_pet_passport_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiEchinococcusTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of product')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, help_text='Time', null=True)),
                ('dosage', models.CharField(help_text='Specify dosage, e.g. "5mg twice a day"', max_length=50, verbose_name='Dosage')),
                ('duration', models.CharField(help_text='Specify duration, e.g. "7 days"', max_length=50, verbose_name='Duration')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_entry', models.DateField(verbose_name='Date of the entry')),
                ('doctor', models.CharField(max_length=100)),
                ('declaration', models.TextField(default='The animal show no signs of diseases and is fit to be transported for the intended journey')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalisationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_entry', models.DateField(verbose_name='Date of the entry')),
                ('doctor', models.CharField(max_length=100)),
                ('legalising_body', models.TextField(verbose_name='Legalising body')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of product')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, help_text='Time', null=True)),
                ('dosage', models.CharField(help_text='Specify dosage, e.g. "5mg twice a day"', max_length=50, verbose_name='Dosage')),
                ('duration', models.CharField(help_text='Specify duration, e.g. "7 days"', max_length=50, verbose_name='Duration')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_entry', models.DateField(verbose_name='Date of the entry')),
                ('doctor', models.CharField(max_length=100)),
                ('reason_for_visit', models.TextField(help_text='Description of the problem or reason for the visit', verbose_name='Reason for visit')),
                ('general_health', models.TextField(blank=True, null=True, verbose_name='General health')),
                ('body_condition_score', models.IntegerField(blank=True, help_text='Assessment of body condition (1 = underweight, 9 = obese)', null=True, verbose_name='Body Condition Score (1-9)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature of the animal', max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, verbose_name='Heart rate (bpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True, verbose_name='Respiratory rate')),
                ('mucous_membrane_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mucous Membrane Color')),
                ('hydration_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hydration Status')),
                ('skin_and_coat_condition', models.TextField(blank=True, null=True, verbose_name='Skin and Coat Condition')),
                ('teeth_and_gums', models.TextField(blank=True, null=True, verbose_name='Teeth and Gums')),
                ('eyes_ears_nose', models.TextField(blank=True, null=True, verbose_name='Eyes, Ears, and Nose')),
                ('treatment_performed', models.TextField(help_text='Description of the Treatment', verbose_name='Treatment Carried Out')),
                ('diagnosis', models.TextField(blank=True, help_text='Description of the final diagnosis', null=True, verbose_name='Diagnosis')),
                ('follow_up', models.BooleanField(default=False, verbose_name='Follow-up Required?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Examination Notes')),
                ('blood_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.bloodtest', verbose_name='Blood Test')),
                ('fecal_exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.fecalexam', verbose_name='Fecal Analysis')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('urine_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.urinalysis', verbose_name='Urine Analysis')),
                ('vaccinations', models.ManyToManyField(blank=True, related_name='examinations_vaccinations', to='medicine.vaccine', verbose_name='Vaccination Applied')),
                ('medications', models.ManyToManyField(blank=True, related_name='examinations_medications', to='records.medication', verbose_name='Medications Prescribed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherAntiParasiteTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of product')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, help_text='Time', null=True)),
                ('dosage', models.CharField(help_text='Specify dosage, e.g. "5mg twice a day"', max_length=50, verbose_name='Dosage')),
                ('duration', models.CharField(help_text='Specify duration, e.g. "7 days"', max_length=50, verbose_name='Duration')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_field', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of vaccine')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Batch number')),
                ('date_of_vaccination', models.DateField(verbose_name='Date of vaccination')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RabiesAntibodyTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_entry', models.DateField(verbose_name='Date of the entry')),
                ('doctor', models.CharField(max_length=100)),
                ('declaration', models.TextField(default='I, the undersigned, confirm that I have seen an official record stating that the rabies antibody titration test performed at an EU-approved laboratory on a sample of blood collected on the date mentioned below from the above described animal proved a response to anti-rabies vaccination at a level of serum neutralising antibody equal to or greater than 0.5 IU/ml.')),
                ('sample_collected_on', models.DateField(verbose_name='Sample collected on')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RabiesVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_and_name', models.CharField(max_length=50, verbose_name='Manufacturer and name of vaccine')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Batch number')),
                ('date_of_vaccination', models.DateField(verbose_name='Date of vaccination')),
                ('valid_until', models.DateField(verbose_name='Valid until')),
                ('valid_from', models.DateField(verbose_name='Valid from')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
