# Generated by Django 5.2 on 2025-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationrecord',
            name='duration',
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='valid_until',
            field=models.DateField(default='2025-05-05', help_text='Specify valid until date', max_length=50, verbose_name='Valid Until'),
            preserve_default=False,
        ),
    ]
