# Generated by Django 5.2 on 2025-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_medicationrecord_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True, verbose_name='Date of the entry'),
        ),
    ]
