# Generated by Django 5.2 on 2025-05-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_medicalexaminationrecord_date_of_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalExaminationRecord',
        ),
    ]
