# Generated by Django 5.2 on 2025-05-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_rename_urinalysis_urinealysis'),
        ('records', '0005_medicalexaminationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='blood_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.bloodtest', verbose_name='Blood Test'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='fecal_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.fecalexam', verbose_name='Fecal Analysis'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='urine_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.urinealysis', verbose_name='Urine Analysis'),
        ),
    ]
