# Generated by Django 5.2 on 2025-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_fecal_exam_medicalexaminationrecord_fecal_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexaminationrecord',
            name='exam_type',
            field=models.CharField(choices=[('primary', 'Primary Examination'), ('follow_up', 'Follow-up Examination')], default='primary', help_text='Indicates whether this is an initial examination or a follow-up', max_length=20, verbose_name='Examination Type'),
        ),
    ]
