# Generated by Django 5.2 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_medicalexaminationrecord_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalexaminationrecord',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='medicalexaminationrecord',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='medicalexaminationrecord',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='records.medicationrecord', verbose_name='Medications Prescribed'),
        ),
        migrations.AddField(
            model_name='medicalexaminationrecord',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='records.vaccinationrecord', verbose_name='Vaccinations Applied'),
        ),
    ]
