# Generated by Django 5.2 on 2025-05-09 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_owner_appuser_clinic_address_and_more'),
        ('records', '0009_remove_medicalexaminationrecord_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexaminationrecord',
            name='clinic',
            field=models.ManyToManyField(related_name='clinic_records', to='accounts.clinic'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='date_of_entry',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of the entry'),
        ),
    ]
