# Generated by Django 5.2 on 2025-05-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_owner_appuser_clinic_address_and_more'),
        ('records', '0012_remove_medicalexaminationrecord_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='clinic',
            field=models.ForeignKey(help_text='Clinic where the examination was conducted', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_records', to='accounts.clinic', verbose_name='Clinic'),
        ),
    ]
