# Generated by Django 5.2 on 2025-05-26 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_medicalexaminationrecord_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of intake'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='dosage',
            field=models.CharField(blank=True, help_text='Specify dosage, if different from reccomended', max_length=50, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of intake', null=True),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='valid_until',
            field=models.DateField(help_text='Specify valid until date', verbose_name='Valid Until'),
        ),
    ]
