# Generated by Django 5.2 on 2025-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_medicationrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrecord',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of intake', null=True, verbose_name='Time of intake'),
        ),
    ]
