# Generated by Django 5.2 on 2025-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_medicationrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Manufacturer'),
        ),
    ]
