# Generated by Django 5.2 on 2025-05-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_alter_medicationrecord_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='date_of_entry',
            field=models.DateField(default=datetime.date.today, help_text='Date of entry', verbose_name='Date of entry'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Date of intake', verbose_name='Date of intake'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='dosage',
            field=models.CharField(blank=True, help_text='Specify dosage, if different from recommended', max_length=50, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='medicationrecord',
            name='valid_until',
            field=models.DateField(help_text='Valid until date', verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date_of_vaccination',
            field=models.DateField(default=datetime.date.today, help_text='Date of vaccination', verbose_name='Date of vaccination'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='manufacture_date',
            field=models.DateField(help_text='Manufacture date', verbose_name='Manufacture date'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='valid_from',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Valid from date', null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='valid_until',
            field=models.DateField(help_text='Valid until date', verbose_name='Valid until'),
        ),
    ]
