# Generated by Django 5.2 on 2025-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_medicalexaminationrecord_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='doctor',
            field=models.CharField(max_length=100, verbose_name='Name of attending veterinarian'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='follow_up',
            field=models.BooleanField(default=False, help_text='Follow-up Required?', verbose_name='Follow-up Required?'),
        ),
    ]
