# Generated by Django 5.2 on 2025-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_medicalexaminationrecord_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch number'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='manufacture_date',
            field=models.DateField(blank=True, help_text='Manufacture date', null=True, verbose_name='Manufacture date'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Manufacturer'),
        ),
    ]
