# Generated by Django 5.2 on 2025-06-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_medicationrecord_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='MedicalExaminationRecord',
            name='clinic',
            field=models.ForeignKey(help_text='Clinic where the examination was conducted', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_records', to='accounts.clinic', verbose_name='Clinic'),
        ),
    ]
