# Generated by Django 5.2 on 2025-06-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_clinic_delete_owner_alter_appuser_is_active_and_more'),
        ('records', '0020_alter_medicalexaminationrecord_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='MedicalExaminationRecord',
            name='clinic',
            field=models.ForeignKey(help_text='Clinic where the examination was conducted', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_records', to='accounts.clinic', verbose_name='Clinic'),
        ),
    ]
