# Generated by Django 5.2 on 2025-06-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_medicalexaminationrecord_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='clinic',
            field=models.ForeignKey(help_text='Clinic where the examination was conducted', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_records', to=settings.AUTH_USER_MODEL, verbose_name='Clinic'),
        ),
    ]
