# Generated by Django 5.2 on 2025-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_alter_medicalexaminationrecord_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='body_condition_score',
            field=models.IntegerField(blank=True, default='Not measured', help_text='Assessment of body condition (1 = underweight, 9 = obese)', null=True, verbose_name='Body Condition Score (1-9)'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='diagnosis',
            field=models.TextField(blank=True, default='Not diagnosed', help_text='Description of the final diagnosis', null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='eyes_ears_nose',
            field=models.TextField(blank=True, default='Not examined', null=True, verbose_name='Eyes, Ears, and Nose'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='general_health',
            field=models.TextField(blank=True, default='Not measured', null=True, verbose_name='General health'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, default='Not measured', help_text='Heart rate in beats per minute', null=True, verbose_name='Heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='hydration_status',
            field=models.CharField(blank=True, default='Not examined', max_length=50, null=True, verbose_name='Hydration Status'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='mucous_membrane_color',
            field=models.CharField(blank=True, default='Not examined', max_length=50, null=True, verbose_name='Mucous Membrane Color'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, default='Not measured', help_text='Respiratory rate in breaths per minute', null=True, verbose_name='Respiratory rate'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='skin_and_coat_condition',
            field=models.TextField(blank=True, default='Not examined', null=True, verbose_name='Skin and Coat Condition'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='teeth_and_gums',
            field=models.TextField(blank=True, default='Not examined', null=True, verbose_name='Teeth and Gums'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default='Not measured', help_text='Body temperature of the animal', max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
