# Generated by Django 5.2 on 2025-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_alter_medicalexaminationrecord_body_condition_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='body_condition_score',
            field=models.IntegerField(blank=True, help_text='Assessment of body condition (1 = underweight, 9 = obese)', null=True, verbose_name='Body Condition Score (1-9)'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, verbose_name='Heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True, verbose_name='Respiratory rate'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature of the animal', max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
