# Generated by Django 5.2 on 2025-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_alter_medicalexaminationrecord_body_condition_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='is_wrong',
            field=models.BooleanField(default=False, verbose_name='Is wrong'),
        ),
    ]
