# Generated by Django 5.2 on 2025-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_vaccinationrecord_is_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Is editable'),
        ),
    ]
