services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
      - static_volume:/app/collect_static
      - media_volume:/app/media
    command: sh -c "python manage.py migrate &&
      python manage.py loaddata .\pet_mvp\accounts\fixtures\clinics.json &&
      python manage.py collectstatic --noinput &&
      python manage.py compilemessages &&
      python caller.py &&
      gunicorn --bind=0.0.0.0:8000 pet_mvp.wsgi:application"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A pet_mvp worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A pet_mvp beat --loglevel=info
    depends_on:
      - redis
      - app
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  static_volume:
  media_volume:
  redis_data:
