services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

#  celery:
#    build: .
#    command: celery -A HairSaloon worker --loglevel=info
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
#      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
#    env_file:
#      - .env