# Generated by Django 5.2 on 2025-05-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('records', '0003_alter_medicalexaminationrecord_date_of_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urinalysis',
            new_name='UrineAnalysis',
        ),
    ]
