# Generated by Django 5.2 on 2025-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_rename_urinalysis_urineanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Analysis'), ('fecal', 'Fecal Exam'), ('other', 'Other')], max_length=20, verbose_name='Test Type')),
                ('result', models.TextField(help_text='Details of the test result', verbose_name='Test Result')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('date_conducted', models.DateField(auto_now_add=True, verbose_name='Date Conducted')),
            ],
        ),
    ]
