# Generated by Django 5.2 on 2025-05-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_animaltest'),
        ('records', '0004_delete_medicalexaminationrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodTest',
        ),
        migrations.DeleteModel(
            name='FecalExam',
        ),
        migrations.DeleteModel(
            name='UrineAnalysis',
        ),
    ]
