# Generated by Django 5.2 on 2025-05-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_bloodtest_fecalexam_urinalysis_delete_animaltest'),
        ('records', '0005_medicalexaminationrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urinalysis',
            new_name='UrineAlysis',
        ),
    ]
