# Generated by Django 5.2 on 2025-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_rename_urinalysis_urinealysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodtest',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fecalexam',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='urinealysis',
            old_name='test_name',
            new_name='name',
        ),
    ]
