# Generated by Django 5.2 on 2025-05-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_rename_test_name_bloodtest_name_and_more'),
        ('records', '0007_rename_fecal_exam_medicalexaminationrecord_fecal_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FecalExam',
            new_name='FecalTest',
        ),
        migrations.RenameModel(
            old_name='UrineAlysis',
            new_name='UrineTest',
        ),
    ]
