# Generated by Django 5.2 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_rename_fecalexam_fecaltest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='date_conducted',
            field=models.DateField(help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
        migrations.AlterField(
            model_name='fecaltest',
            name='date_conducted',
            field=models.DateField(help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='date_conducted',
            field=models.DateField(help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
    ]
