# Generated by Django 5.2 on 2025-05-09 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_alter_bloodtest_date_conducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='date_conducted',
            field=models.DateField(default=datetime.date.today, help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
        migrations.AlterField(
            model_name='fecaltest',
            name='date_conducted',
            field=models.DateField(default=datetime.date.today, help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='date_conducted',
            field=models.DateField(default=datetime.date.today, help_text='Date when the test was conducted', verbose_name='Date Conducted'),
        ),
    ]
