# Generated by Django 5.2 on 2025-05-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_alter_bloodtest_date_conducted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fecaltest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='urinetest',
            name='name',
        ),
    ]
