# Generated by Django 5.2 on 2025-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_remove_bloodtest_name_remove_fecaltest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name of vaccine'),
        ),
        migrations.AddField(
            model_name='drug',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name of vaccine'),
        ),
        migrations.AddField(
            model_name='drug',
            name='notes_bg',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='drug',
            name='notes_en',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name of vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name of vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notes_bg',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notes_en',
            field=models.TextField(null=True, verbose_name='Notes'),
        ),
    ]
