# Generated by Django 5.2 on 2025-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_drug_name_bg_drug_name_en_drug_notes_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='recommended_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days after which the treatment/vaccine should be repeated. Leave blank if not applicable.', null=True, verbose_name='Recommended interval (days)'),
        ),
        migrations.AddField(
            model_name='drug',
            name='suitable_for',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', help_text='Select whether is for cats or dogs.', max_length=10, verbose_name='Suitable for'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='recommended_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days after which the treatment/vaccine should be repeated. Leave blank if not applicable.', null=True, verbose_name='Recommended interval (days)'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='suitable_for',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', help_text='Select whether is for cats or dogs.', max_length=10, verbose_name='Suitable for'),
            preserve_default=False,
        ),
    ]
