# Generated by Django 5.2 on 2025-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_drug_recommended_interval_days_drug_suitable_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecaltest',
            name='blood_presence',
            field=models.BooleanField(default=False, help_text='Blood Presence in Stool', verbose_name='Blood Presence in Stool'),
        ),
        migrations.AlterField(
            model_name='fecaltest',
            name='parasites_detected',
            field=models.BooleanField(default=False, help_text='Parasites Detected', verbose_name='Parasites Detected'),
        ),
    ]
