# Generated by Django 5.2 on 2025-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_alter_fecaltest_blood_presence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_antiparasite',
            field=models.BooleanField(default=False, verbose_name='Is antiparasite'),
        ),
    ]
