# Generated by Django 5.2 on 2025-06-03 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petaccesslog',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Access Time'),
        ),
        migrations.AlterField(
            model_name='petaccesslog',
            name='accessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Accessed By'),
        ),
        migrations.AlterField(
            model_name='petaccesslog',
            name='method',
            field=models.CharField(choices=[('qr', 'QR Code'), ('link', 'Shared Link'), ('owner', 'Owner'), ('clinic', 'Clinic View')], default='owner', max_length=50, verbose_name='Access Method'),
        ),
    ]
