# Generated by Django 5.2 on 2025-05-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0001_initial'),
        ('pets', '0004_pet_can_add_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petaccesscode',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_access_code', to='pets.pet'),
        ),
    ]
