# Generated by Django 5.2 on 2025-06-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0004_petsharetoken'),
        ('accounts', '0008_alter_appuser_city_alter_appuser_country_and_more'),
        ('pets', '0013_remove_pet_can_add_treatments'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetPetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('granted_by', models.CharField(choices=[('code', 'Access Code'), ('qr', 'QR Code')], max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
            ],
        ),
    ]
