# Generated by Django 5.2 on 2025-06-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0005_vetpetaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetaccesstoken',
            name='pet',
        ),
        migrations.DeleteModel(
            name='PetShareToken',
        ),
        migrations.DeleteModel(
            name='VetAccessToken',
        ),
    ]
