# Generated by Django 5.2 on 2025-06-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0008_alter_vetpetaccess_vet'),
        ('accounts', '0010_delete_clinic_delete_owner_alter_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='VetPetAccess',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic'),
        ),
    ]
