# Generated by Django 5.2 on 2025-04-24 10:48

import django.db.models.deletion
import pet_mvp.pets.utils
import pet_mvp.pets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('species', models.CharField(max_length=50, verbose_name='Species')),
                ('breed', models.CharField(max_length=50, verbose_name='Breed')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='Sex')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('features', models.CharField(max_length=255, verbose_name='Any notable or discernible features or characteristics')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pet_mvp.pets.utils.pet_directory_path, verbose_name='Photo')),
                ('current_weight', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Current weight')),
                ('passport_number', models.CharField(max_length=12, unique=True, validators=[pet_mvp.pets.validators.validate_passport_number], verbose_name='Passport Number')),
                ('owners', models.ManyToManyField(related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('type', models.CharField(max_length=11, verbose_name='Type')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Tattoo alphanumeric code')),
                ('date_of_application', models.DateField(verbose_name='Date of application of the tattoo')),
                ('date_of_reading', models.DateField(verbose_name='Date of reading of the tattoo')),
                ('location', models.CharField(max_length=255, verbose_name='Location of the tattoo')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transponder',
            fields=[
                ('type', models.CharField(max_length=11, verbose_name='Type')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[pet_mvp.pets.validators.validate_transponder_code], verbose_name='Transponder alphanumeric code')),
                ('date_of_application', models.DateField(blank=True, null=True, verbose_name='Date of application or reading of the transponder')),
                ('date_of_reading', models.DateField(blank=True, null=True, verbose_name='Date of application or reading of the transponder')),
                ('location', models.CharField(max_length=255, verbose_name='Location of the transponder')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
