# Generated by Django 5.2 on 2025-04-26 15:35

import pet_mvp.pets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passport_number',
            field=models.CharField(error_messages={'unique': 'A pet with this details already exists.'}, max_length=12, unique=True, validators=[pet_mvp.pets.validators.validate_passport_number], verbose_name='Passport Number'),
        ),
    ]
