# Generated by Django 5.2 on 2025-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='can_add_vaccines',
            field=models.BooleanField(default=True, help_text='Controls if the owner can add vaccines.', verbose_name='Can add vaccines?'),
        ),
    ]
