# Generated by Django 5.2 on 2025-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_can_add_vaccines'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='can_add_treatments',
            field=models.BooleanField(default=True, help_text='Controls if the owner can add treatments.', verbose_name='Can add treatments?'),
        ),
    ]
