# Generated by Django 5.2 on 2025-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_can_add_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed_bg',
            field=models.CharField(max_length=50, null=True, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color_bg',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='pet',
            name='features_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Any notable or discernible features or characteristics'),
        ),
        migrations.AddField(
            model_name='pet',
            name='features_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Any notable or discernible features or characteristics'),
        ),
        migrations.AddField(
            model_name='pet',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pet',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species_bg',
            field=models.CharField(max_length=50, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='location_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Location of the tattoo'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Location of the tattoo'),
        ),
        migrations.AddField(
            model_name='transponder',
            name='location_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Location of the transponder'),
        ),
        migrations.AddField(
            model_name='transponder',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Location of the transponder'),
        ),
    ]
