# Generated by Django 5.2 on 2025-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_breed_bg_pet_breed_en_pet_color_bg_pet_color_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex_bg',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex_en',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True, verbose_name='Sex'),
        ),
    ]
