# Generated by Django 5.2 on 2025-05-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_sex_bg_pet_sex_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex_bg',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex_en',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species_bg',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50, null=True, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species_en',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50, null=True, verbose_name='Species'),
        ),
    ]
