# Generated by Django 5.2 on 2025-05-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_sex_alter_pet_sex_bg_alter_pet_sex_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed_bg',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed_en',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex_bg',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex_en',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species_bg',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species_en',
        ),
    ]
