# Generated by Django 5.2 on 2025-05-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_pet_species_bg_pet_species_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species_bg',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species_en',
        ),
    ]
