# Generated by Django 5.2 on 2025-05-23 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_remove_pet_species_bg_remove_pet_species_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pending_owners',
            field=models.ManyToManyField(blank=True, related_name='pending_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
