# Generated by Django 5.2 on 2025-06-03 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_remove_pet_pending_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pending_owners',
            field=models.ManyToManyField(blank=True, related_name='pending_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
