# Generated by Django 5.2 on 2025-06-04 16:52

import pet_mvp.pets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_pet_pending_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passport_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A pet with this details already exists.'}, max_length=12, null=True, unique=True, validators=[pet_mvp.pets.validators.validate_passport_number], verbose_name='Passport Number'),
        ),
    ]
