# Generated by Django 5.2 on 2025-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_alter_pet_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passport_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A pet with this details already exists.'}, max_length=12, null=True, unique=True, verbose_name='Passport Number'),
        ),
    ]
