# Generated by Django 5.2 on 2025-05-18 15:00

import django.utils.timezone
import pet_mvp.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_owner_appuser_clinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clinic address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clinic name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_owner',
            field=models.BooleanField(default=True, verbose_name='Owner status'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[pet_mvp.accounts.validators.phone_number_validator], verbose_name='Phone number'),
        ),
    ]
