# Generated by Django 5.2 on 2025-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_city_alter_appuser_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='default_language',
            field=models.CharField(choices=[('bg', 'BG'), ('en', 'EN')], default='bg'),
        ),
    ]
