# Generated by Django 5.2 on 2025-05-23 18:45

from django.db import migrations


def create_superuser(apps, schema_editor):

    User = apps.get_model('accounts', 'Clinic')

    User.objects.create_superuser(
        email='admin@pet-mvp.com',
        password='1234',
        first_name='Admin',
        last_name='Superuser',
        city='Варна',
        country='България',
        phone_number='0887888888',
        is_owner=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_default_language'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
