# Generated by Django 5.2 on 2025-05-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Phone number'),
        ),
    ]
