# Generated by Django 5.2 on 2025-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Clinic approved'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts. If the user is vet clinic and not active, an email with activation link will be sent one valid email address is entered', verbose_name='Active'),
        ),
    ]
