# Generated by Django 5.2 on 2025-05-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appuser_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone number'),
        ),
    ]
