# Generated by Django 5.2 on 2025-06-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_city_alter_appuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number'),
        ),
    ]
