# Generated by Django 5.2 on 2025-06-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts. If the user is vet clinic and not active, an email with activation link will be sent once a valid email address is entered.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Clinic approved'),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='Clinic name')),
                ('clinic_address', models.CharField(max_length=255, verbose_name='Clinic address')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Clinic approved')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('user', models.OneToOneField(limit_choices_to={'is_owner': False}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('user', models.OneToOneField(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
