# Generated by Django 5.2 on 2025-06-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_clinic_delete_owner_alter_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
    ]
