# Generated by Django 5.2 on 2025-06-05 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_appuser_clinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_owner': False}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
