# Generated by Django 5.2 on 2025-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_clinic_user_alter_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_clinic',
            field=models.BooleanField(default=False, verbose_name='Clinic status'),
        ),
    ]
