# Generated by Django 5.2 on 2025-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appuser_created_at_appuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
