# Generated by Django 5.2 on 2025-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_clinic_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_name',
            new_name='name',
        ),
    ]
